### ISSUE TITLE
Crash with ruby 3 and Rails 6.0

### ISSUE THREAD

**Issue by mjobin-mdsol** [iangreenleaf/native_enum#21]
works with ruby 2.7 and rails 6.0

```
vendor/bundle/ruby/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/mysql/schema_statements.rb:101:in `type_to_sql'
vendor/bundle/ruby/3.0.0/gems/native_enum-2.0.0/lib/connection_adapters/mysql2.rb:40:in `type_to_sql_with_enum'
vendor/bundle/ruby/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `type_to_sql'
vendor/bundle/ruby/3.0.0/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:30:in `visit_ColumnDefinition'
```

**Comment by iangreenleaf** [comment]
Thanks for the bug report. I think I am going to be sunsetting this gem. It has lost half its functionality with Rails 6 (which isn't officially supported) and I think the demand for this functionality has decreased substantially. I am not personally using it any more so I lack the motivation to sink a lot of time into updating it.
